require('modules.tools.filetree')
-- require('modules.tools.telescope')
require('modules.tools.fuzzy-finding')
require('modules.tools.colorizer')
require('modules.tools.indent-guides')
require('modules.tools.searcher')
